### PR TITLE
Resolve #1781, #1783, #1799, #1800, #1801

### LINKED ISSUE #1781: Let users to add ERC20 in user setting

### LINKED ISSUE #1783: Integrate ethContracts api

### LINKED ISSUE #1799: Split tests into multiple stages

### LINKED ISSUE #1800: Update Puppeteer

### LINKED ISSUE #1801: Fix broken tests

### PR DESCRIPTION
**Pull request by InVincible2016**
- Resolve #1781 Allow users to add more ERC20
- Resolve #1783 Integrate ethContracts api
- Resolve #1799 Split tests into multiple stages
- Resolve #1800 Update Puppeteer
- Resolve #1801 Fix broken tests

### CODE REVIEW

File: src/components/AccountsManagementComponent.jsx [hunk 1]
```diff
@@ -548,7 +552,7 @@ class AccountsManagementComponent extends Component {
       >
         <Container className={classes.container}>
           <Grid container>
-            <Grid item md={6} xs={12} className={classes.upperBigGridItem}>
+            <Grid item lg={6} xs={12} className={classes.upperBigGridItem}>
```
Comment (timothywangdev) [inline src/components/AccountsManagementComponent.jsx:555]: why change this?

File: src/components/AddNewTokenComponent.js [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+import TextField from '@material-ui/core/TextField'
+import TokenSearchIcon from '../images/tokensearch.svg'
+
+const useStyle = makeStyles(theme => ({
+  drawerPapper: {
+    maxWidth: '480px',
+    width: '100%'
+  },
+  title: {
+    padding: '30px 20px'
```
Comment (timothywangdev) [inline src/components/AddNewTokenComponent.js:34]: use theme.spacing

File: src/components/AddNewTokenComponent.js [hunk 3]
```diff
@@ -0,0 +1,222 @@
...
+  },
+  listItem: {
+    padding: '10px'
```
Comment (timothywangdev) [inline src/components/AddNewTokenComponent.js:37]: use theme.spacing

File: src/components/AddNewTokenComponent.js [hunk 4]
```diff
@@ -0,0 +1,222 @@
...
+  },
+  listItemIcon: {
+    marginRight: '20px'
```
Comment (timothywangdev) [inline src/components/AddNewTokenComponent.js:40]: use theme.spacing

File: src/components/AddNewTokenComponent.js [hunk 5]
```diff
@@ -0,0 +1,222 @@
...
+      <Box display='relative' padding='20px 30px'>
+        <Typography variant='h3'>Add Tokens</Typography>
+        <IconButton onClick={onClose} className={classes.closeButton}>
+          <CloseIcon className={classes.closeIcon} />
+        </IconButton>
+      </Box>
+      <Divider />
+      <Box display='flex' flexDirection='column' padding='20px 30px'>
+        <FormControl variant='outlined'>
+          <InputLabel>Add to Account</InputLabel>
```
Comment (timothywangdev) [inline src/components/AddNewTokenComponent.js:186]: Add to Wallet

File: src/containers/AccountsManagementContainer.jsx [hunk 6]
```diff
@@ -85,20 +113,66 @@ class AccountsManagementContainer extends Component {
...
+          addCryptoAccounts={addCryptoAccounts}
+          actionsPending={actionsPending}
+          modifyCryptoAccountsName={this.modifyCryptoAccountsName}
+          removeCryptoAccounts={this.removeCryptoAccounts}
+          handleTransferFrom={this.handleTransferFrom}
+          onAddToken={this.toggleAddTokenDrawer}
+          online={online}
+          currency={currency}
+        />
+        {!addTokenDrawer && (
```
Comment (timothywangdev) [inline src/containers/AccountsManagementContainer.jsx:167]: buggy

File: src/containers/AccountsManagementContainer.jsx [hunk 7]
```diff
@@ -77,6 +85,26 @@ class AccountsManagementContainer extends Component {
     return categorizedAccounts
   }
 
+  getWallets = cryptoAccounts => {
```
Comment (timothywangdev) [inline src/containers/AccountsManagementContainer.jsx:88]: comment on what this func does

File: src/erc20Tokens.js [hunk 8]
```diff
@@ -1,42 +1,42 @@
-import env from './typedEnv'
+// import env from './typedEnv'
```
Comment (timothywangdev) [inline src/erc20Tokens.js:1]: remove

File: src/erc20Tokens.js [hunk 9]
```diff
@@ -1,42 +1,42 @@
...
-  'usd-coin': {
-    'rinkeby': '0xF76eB2f15a960A5d96d046a00007EFd737e5ea14',
-    'mainnet': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
-  },
-  'true-usd': {
-    'rinkeby': '0x4aacB7f0bA0A5CfF9A8a5e8C0F24626Ee9FDA4a6',
-    'mainnet': '0x0000000000085d4780B73119b644AE5ecd22b376'
-  }
-}
+// const addressMap = {
```
Comment (timothywangdev) [inline src/erc20Tokens.js:3]: remove

File: src/erc20Tokens.js [hunk 10]
```diff
@@ -1,42 +1,42 @@
...
-  'usd-coin':
-    env.REACT_APP_ENV === 'test' || env.REACT_APP_ENV === 'staging'
-      ? addressMap['usd-coin']['rinkeby']
-      : addressMap['usd-coin']['mainnet'],
-  'true-usd':
-    env.REACT_APP_ENV === 'test' || env.REACT_APP_ENV === 'staging'
-      ? addressMap['true-usd']['rinkeby']
-      : addressMap['true-usd']['mainnet'],
-}
+// const erc20TokensAddress = {
```
Comment (timothywangdev) [inline src/erc20Tokens.js:22]: remove

File: src/erc20Tokens.js [hunk 11]
```diff
@@ -1,42 +1,42 @@
...
+//       : addressMap['usd-coin']['mainnet'],
+//   'true-usd':
+//     env.REACT_APP_ENV === 'test' || env.REACT_APP_ENV === 'staging'
+//       ? addressMap['true-usd']['rinkeby']
+//       : addressMap['true-usd']['mainnet']
+// }
 
-const erc20TokensList = Object.keys(erc20TokensAddress)
-export { erc20TokensAddress, erc20TokensList }
+// const erc20TokensList = Object.keys(erc20TokensAddress)
```
Comment (timothywangdev) [inline src/erc20Tokens.js:41]: remove

File: src/erc20Tokens.js [hunk 12]
```diff
@@ -1,42 +1,42 @@
...
+// export { erc20TokensAddress, erc20TokensList }
```
Comment (timothywangdev) [inline src/erc20Tokens.js:42]: remove

File: src/tests/e2e/pages/disconnect.page.js [hunk 13]
```diff
@@ -5,10 +5,11 @@ import pWaitFor from 'p-wait-for'
 import ERC20_ABI from '../../../contracts/ERC20'
 import SimpleMultiSigContractArtifacts from '../../../contracts/SimpleMultiSig.json'
 import url from '../../../url'
-import { erc20TokensAddress } from '../../../erc20Tokens'
 import { CRYPTO_ACCOUNTS } from '../mocks/cryptoAccounts'
 log.setDefaultLevel('info')
 const NETWORK_ID = 4
+const DAI_ADDRESS = '0x4aacB7f0bA0A5CfF9A8a5e8C0F24626Ee9FDA4a6'
```
Comment (timothywangdev) [inline src/tests/e2e/pages/disconnect.page.js:11]: move dai address to a config file and import

File: src/tests/e2e/utils/requestInterceptor.js [hunk 14]
```diff
@@ -2,11 +2,10 @@
 declare var Base64: any
 declare var log: any
 
-import { erc20TokensAddress } from '../../../erc20Tokens.js'
 const _ = require('lodash')
 const chalk = require('chalk')
 
-const CONTRACT_ADDR = erc20TokensAddress['dai'].toLowerCase()
+const CONTRACT_ADDR = '0x4aacB7f0bA0A5CfF9A8a5e8C0F24626Ee9FDA4a6'.toLowerCase()
```
Comment (timothywangdev) [inline src/tests/e2e/utils/requestInterceptor.js:8]: move dai address to a config file and import

File: src/tokens.js [hunk 15]
```diff
@@ -25,111 +23,63 @@ export const cryptoSelections = [
...
+  return ethContracts[cryptoType]
+    ? ethContracts[cryptoType].symbol
+    : cryptoSelections[cryptoType].symbol
 }
 
 export function getCrypto (cryptoType) {
-  return cryptoSelections.find(crypto => {
-    return cryptoType === crypto.cryptoType
-  })
+  const ethContracts = getEthContracts()
```
Comment (timothywangdev) [inline src/tokens.js:54]: what about ethereum and bitcoin?

File: src/url.js [hunk 16]
```diff
@@ -57,33 +58,24 @@ function getBtcExplorerTx (txHash) {
...
-    case 'usd-coin':
-    case 'true-usd':
-      return getEthExplorerTx(txHash)
-    case 'bitcoin':
-      return getBtcExplorerTx(txHash)
-    default:
-      throw new Error(`Invalid cryptoType: ${cryptoType}`)
+  if (cryptoType === 'bitcoin') {
+    return getBtcExplorerTx(txHash)
+  } else if (cryptoType === 'ethereum' || getEthContracts()[cryptoType].erc20) {
```
Comment (timothywangdev) [inline src/url.js:63]: use isERC20()

File: src/url.js [hunk 17]
```diff
@@ -57,33 +58,24 @@ function getBtcExplorerTx (txHash) {
...
-      return getEthExplorerToken(erc20TokensAddress[cryptoType], address)
-    case 'bitcoin':
-      return getBtcExplorerAddress(address)
-    default:
-      throw new Error(`Invalid cryptoType: ${cryptoType}`)
+  if (cryptoType === 'bitcoin') {
+    return getBtcExplorerAddress(address)
+  } else if (cryptoType === 'ethereum') {
+    return getEthExplorerAddress(address)
+  } else if (getEthContracts()[cryptoType].erc20) {
```
Comment (timothywangdev) [inline src/url.js:75]: use isERC20()

File: src/wallets/coinbaseOAuthWallet.js [hunk 18]
```diff
@@ -18,19 +18,10 @@ export default class CoinbaseOAuthWallet implements IWallet<AccountData> {
...
-          this.account = new EthereumAccount(accountData)
-          break
-        case 'bitcoin':
-          this.account = new BitcoinAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
+      if (accountData.cryptoType === 'bitcoin') {
+        this.account = new BitcoinAccount(accountData)
+      } else {
```
Comment (timothywangdev) [inline src/wallets/coinbaseOAuthWallet.js:23]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/coinbaseOAuthWallet.js [hunk 19]
```diff
@@ -116,12 +107,10 @@ export default class CoinbaseOAuthWallet implements IWallet<AccountData> {
...
 
   async newAccount (name: string, cryptoType: string, options?: Object): Promise<IAccount> {
-    if (['ethereum', ...erc20TokensList].includes(cryptoType)) {
-      return this._newEthereumAccount(name, cryptoType, options)
-    } else if (cryptoType === 'bitcoin') {
+    if (cryptoType === 'bitcoin') {
       return this._newBitcoinAccount(name)
     } else {
-      throw new Error('Invalid crypto type')
+      return this._newEthereumAccount(name, cryptoType, options)
```
Comment (timothywangdev) [inline src/wallets/coinbaseOAuthWallet.js:113]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/coinbaseWalletLink.js [hunk 20]
```diff
@@ -33,17 +32,7 @@ export default class CoinbaseWalletLink implements IWallet<AccountData> {
...
-        case 'tether':
-        case 'usd-coin':
-        case 'true-usd':
-        case 'ethereum':
-          this.account = new EthereumAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
-      }
+      this.account = new EthereumAccount(accountData)
```
Comment (timothywangdev) [inline src/wallets/coinbaseWalletLink.js:35]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/coinbaseWalletLink.js [hunk 21]
```diff
@@ -96,11 +85,7 @@ export default class CoinbaseWalletLink implements IWallet<AccountData> {
   }
 
   async newAccount (name: string, cryptoType: string, options?: Object): Promise<IAccount> {
-    if (['ethereum', ...erc20TokensList].includes(cryptoType)) {
-      return this._newEthereumAccount(name, cryptoType, options)
-    } else {
-      throw new Error('Invalid crypto type')
-    }
+    return this._newEthereumAccount(name, cryptoType, options)
```
Comment (timothywangdev) [inline src/wallets/coinbaseWalletLink.js:88]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/drive.js [hunk 22]
```diff
@@ -34,19 +33,10 @@ export default class DriveWallet implements IWallet<AccountData> {
...
-          this.account = new EthereumAccount(accountData)
-          break
-        case 'bitcoin':
-          this.account = new BitcoinAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
+      if (accountData.cryptoType === 'bitcoin') {
+        this.account = new BitcoinAccount(accountData)
+      } else {
```
Comment (timothywangdev) [inline src/wallets/drive.js:38]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/drive.js [hunk 23]
```diff
@@ -168,14 +154,10 @@ export default class DriveWallet implements IWallet<AccountData> {
   }
 
   async newAccount (name: string, cryptoType: string, options?: Object): Promise<IAccount> {
-    if (['bitcoin', 'ethereum', ...erc20TokensList].includes(cryptoType)) {
-      if (cryptoType !== 'bitcoin') {
-        return this._newEthereumAccount(name, cryptoType, options)
-      } else {
-        return this._newBitcoinAccount(name)
-      }
+    if (cryptoType !== 'bitcoin') {
```
Comment (timothywangdev) [inline src/wallets/drive.js:157]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/drive.js [hunk 24]
```diff
@@ -221,7 +203,7 @@ export default class DriveWallet implements IWallet<AccountData> {
           accountData.connected = false
           throw new Error(driveErrors.keyPairDoesNotMatch)
         }
-      } else if (['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
+      } else {
```
Comment (timothywangdev) [inline src/wallets/drive.js:206]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/drive.js [hunk 25]
```diff
@@ -257,7 +239,22 @@ export default class DriveWallet implements IWallet<AccountData> {
...
+      )
+      const signedTxRaw = await this._xPrivSigner(
+        utxosCollected,
+        to,
+        Number(value), // actual value to be sent
+        Number(fee),
+        accountData.hdWalletVariables.nextChangeIndex
+      )
+      return { txHash: await WalletUtils.broadcastBtcRawTx(signedTxRaw) }
+    } else {
```
Comment (timothywangdev) [inline src/wallets/drive.js:257]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/escrow.js [hunk 26]
```diff
@@ -32,19 +31,10 @@ export default class EscrowWallet implements IWallet<AccountData> {
...
-          this.account = new EthereumAccount(accountData)
-          break
-        case 'bitcoin':
-          this.account = new BitcoinAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
+      if (accountData.cryptoType === 'bitcoin') {
+        this.account = new BitcoinAccount(accountData)
+      } else {
```
Comment (timothywangdev) [inline src/wallets/escrow.js:36]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/escrow.js [hunk 27]
```diff
@@ -160,14 +150,10 @@ export default class EscrowWallet implements IWallet<AccountData> {
   }
 
   async newAccount (name: string, cryptoType: string, options?: Object): Promise<IAccount> {
-    if (['bitcoin', 'ethereum', ...erc20TokensList].includes(cryptoType)) {
-      if (cryptoType !== 'bitcoin') {
-        return this._newEthereumAccount(name, cryptoType, options)
-      } else {
-        return this._newBitcoinAccount(name)
-      }
+    if (cryptoType !== 'bitcoin') {
```
Comment (timothywangdev) [inline src/wallets/escrow.js:153]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/escrow.js [hunk 28]
```diff
@@ -205,7 +191,7 @@ export default class EscrowWallet implements IWallet<AccountData> {
           accountData.connected = false
           throw new Error(escrowErrors.keyPairDoesNotMatch)
         }
-      } else if (['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
+      } else {
```
Comment (timothywangdev) [inline src/wallets/escrow.js:194]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/escrow.js [hunk 29]
```diff
@@ -261,7 +246,9 @@ export default class EscrowWallet implements IWallet<AccountData> {
         accountData.hdWalletVariables.nextChangeIndex
       )
     } else {
-      throw new Error('Invalid crypto type')
```
Comment (timothywangdev) [inline src/wallets/escrow.js:264]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/escrow.js [hunk 30]
```diff
@@ -280,7 +267,7 @@ export default class EscrowWallet implements IWallet<AccountData> {
         value,
         addressesPool: accountData.hdWalletVariables.addresses
       })
-    } else if (['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
+    } else {
```
Comment (timothywangdev) [inline src/wallets/escrow.js:270]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/ledger.js [hunk 31]
```diff
@@ -42,19 +41,10 @@ export default class LedgerWallet implements IWallet<AccountData> {
...
-          this.account = new EthereumAccount(accountData)
-          break
-        case 'bitcoin':
-          this.account = new BitcoinAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
+      if (accountData.cryptoType === 'bitcoin') {
+        this.account = new BitcoinAccount(accountData)
+      } else {
```
Comment (timothywangdev) [inline src/wallets/ledger.js:46]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/ledger.js [hunk 32]
```diff
@@ -222,14 +212,10 @@ export default class LedgerWallet implements IWallet<AccountData> {
...
-    if (['bitcoin', 'ethereum', ...erc20TokensList].includes(cryptoType)) {
-      if (cryptoType !== 'bitcoin') {
-        return this._newEthereumAccount(name, cryptoType, options)
-      } else {
-        return this._newBitcoinAccount(name)
-      }
+    if (cryptoType !== 'bitcoin') {
+      return this._newEthereumAccount(name, cryptoType, options)
     } else {
-      throw new Error('Invalid crypto type')
```
Comment (timothywangdev) [inline src/wallets/ledger.js:232]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/ledger.js [hunk 33]
```diff
@@ -246,7 +232,7 @@ export default class LedgerWallet implements IWallet<AccountData> {
         accountData.connected = false
         throw new Error(ledgerErrors.incorrectAccount)
       }
-    } else if (['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
+    } else {
```
Comment (timothywangdev) [inline src/wallets/ledger.js:235]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/ledger.js [hunk 34]
```diff
@@ -278,7 +264,32 @@ export default class LedgerWallet implements IWallet<AccountData> {
...
+        )
+      } catch (e) {
+        if (e.message.match(/has no matching Script/)) {
+          // This error happens when the signing private key does
+          // not match the address/pubkey
+          throw new Error(ledgerErrors.incorrectSigningKey)
+        }
+      }
+      return { txHash: await WalletUtils.broadcastBtcRawTx(signedTxRaw) }
+    } else {
```
Comment (timothywangdev) [inline src/wallets/ledger.js:292]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/metamask.js [hunk 35]
```diff
@@ -21,17 +21,7 @@ export default class MetamaskWallet implements IWallet<AccountData> {
...
-        case 'tether':
-        case 'usd-coin':
-        case 'true-usd':
-        case 'ethereum':
-          this.account = new EthereumAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
-      }
+      this.account = new EthereumAccount(accountData)
```
Comment (timothywangdev) [inline src/wallets/metamask.js:24]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/metamask.js [hunk 36]
```diff
@@ -96,11 +86,7 @@ export default class MetamaskWallet implements IWallet<AccountData> {
   }
 
   async newAccount (name: string, cryptoType: string, options?: Object): Promise<IAccount> {
-    if (['ethereum', ...erc20TokensList].includes(cryptoType)) {
-      return this._newEthereumAccount(name, cryptoType, options)
-    } else {
-      throw new Error('Invalid crypto type')
-    }
+    return this._newEthereumAccount(name, cryptoType, options)
```
Comment (timothywangdev) [inline src/wallets/metamask.js:89]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/walletConnect.js [hunk 37]
```diff
@@ -27,17 +26,7 @@ export default class WalletConnect implements IWallet<AccountData> {
...
-        case 'tether':
-        case 'usd-coin':
-        case 'true-usd':
-        case 'ethereum':
-          this.account = new EthereumAccount(accountData)
-          break
-        default:
-          throw new Error('Invalid crypto type')
-      }
+      this.account = new EthereumAccount(accountData)
```
Comment (timothywangdev) [inline src/wallets/walletConnect.js:29]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/wallets/walletConnect.js [hunk 38]
```diff
@@ -90,11 +79,7 @@ export default class WalletConnect implements IWallet<AccountData> {
   }
 
   async newAccount (name: string, cryptoType: string, options?: Object): Promise<IAccount> {
-    if (['ethereum', ...erc20TokensList].includes(cryptoType)) {
-      return this._newEthereumAccount(name, cryptoType, options)
-    } else {
-      throw new Error('Invalid crypto type')
-    }
+    return this._newEthereumAccount(name, cryptoType, options)
```
Comment (timothywangdev) [inline src/wallets/walletConnect.js:82]: check if its eth or erc20 using isERC20(), throw if cryptoType is invalid

File: src/accounts/EthereumAccount.js [hunk 39]
```diff
@@ -9,16 +9,12 @@ import { getWalletTitle, getWalletConfig } from '../wallet'
...
 import WalletUtils from '../wallets/utils'
 import env from '../typedEnv'
-import { erc20TokensList } from '../erc20Tokens'
 const PLATFORM_TYPE = 'ethereum'
 
 export default class EthereumAccount implements IAccount<AccountData> {
   accountData: AccountData
 
   constructor (accountData: AccountData) {
-    if (!['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/accounts/EthereumAccount.js:19]: Making the check here would make this class component rely on the getAllEthContract request. If that the getAllEthContract request failed, this part would fail too.

File: src/actions/userActions.js [hunk 40]
```diff
@@ -301,6 +301,7 @@ function postLoginPreparation (loginData: any, progress?: Function) {
         // Must try register before getWallet, getCryptoAccounts, and getRecipients
         const userMetaInfo = (await dispatch(register(idToken, profileObj))).value
         const currentTimestamp = moment().unix()
+        await dispatch(getAllEthContracts())
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/actions/userActions.js:304]: Will make it parallel with register

File: src/components/AccountsManagementComponent.jsx (hunk 1 above)
Comment (InVincible2016) [reply src/components/AccountsManagementComponent.jsx:555]: Added a new btn called 'Add New Token' here, have to change the breakpoint to be at larger screen size, otherwise break too soon.

File: src/components/AddNewTokenComponent.js (hunk 4 above)
Comment (InVincible2016) [reply src/components/AddNewTokenComponent.js:40]: fixed

File: src/components/AddNewTokenComponent.js (hunk 5 above)
Comment (InVincible2016) [reply src/components/AddNewTokenComponent.js:186]: fixed

File: src/containers/AccountsManagementContainer.jsx (hunk 6 above)
Comment (InVincible2016) [reply src/containers/AccountsManagementContainer.jsx:167]: fixed

File: src/tests/e2e/utils/requestInterceptor.js (hunk 14 above)
Comment (InVincible2016) [reply src/tests/e2e/utils/requestInterceptor.js:8]: fixed

File: src/App.js [hunk 41]
```diff
@@ -335,19 +334,11 @@ class App extends Component {
...
-    setInterval(
-      () => store.dispatch(getCryptoPrice(['bitcoin', 'ethereum', ...erc20TokensList])),
-      60000
-    )
   }
 
   render () {
     if (!this.state.preloadFinished) {
-      return null
+      return <PreloadingComponent />
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/App.js:341]: Preload is now longer than before because of eth contracts fetching

File: src/actions/accountActions.js [hunk 42]
```diff
@@ -148,36 +149,41 @@ async function _addCryptoAccounts (accountData: Array<AccountData>): Promise<Arr
   return cryptoAccounts
 }
 
-function addCryptoAccounts (accountData: AccountData | Array<AccountData>) {
+function addCryptoAccounts (accountData: AccountData | Array<AccountData>, addToken?: boolean) {
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/actions/accountActions.js:152]: added

File: src/actions/cryptoPriceActions.js [hunk 43]
```diff
@@ -2,32 +2,34 @@
...
-    const { currency } = getState().cryptoPriceReducer
+    // api only accepts lowercase currency symbol
+    const currency = getState().cryptoPriceReducer.currency.toLowerCase()
     return dispatch({
       type: 'GET_CRYPTO_PRICE',
-      payload: _getCryptoPrice(cryptoTypes, currency)
+      payload: async () => {
+        let rv = {}
+        try {
+          // get eth and bitcoin price
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/actions/cryptoPriceActions.js:14]: fixed

File: src/actions/cryptoPriceActions.js [hunk 44]
```diff
@@ -2,32 +2,34 @@
...
-
 function getCryptoPrice (cryptoTypes: Array<string>) {
   return (dispatch: Function, getState: Function) => {
-    const { currency } = getState().cryptoPriceReducer
+    // api only accepts lowercase currency symbol
+    const currency = getState().cryptoPriceReducer.currency.toLowerCase()
     return dispatch({
       type: 'GET_CRYPTO_PRICE',
-      payload: _getCryptoPrice(cryptoTypes, currency)
+      payload: async () => {
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/actions/cryptoPriceActions.js:11]: fixed

File: src/actions/walletActions.js [hunk 45]
```diff
@@ -39,7 +38,7 @@ async function _createCloudWallet (password: string, progress: ?Function) {
           let _wallet = createWallet({ walletType: 'drive' })
           let privateKey
           if (
-            (ethereumBasedAccountData && [...erc20TokensList].includes(cryptoType)) ||
+            (ethereumBasedAccountData && cryptoType !== 'bitcoin') ||
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/actions/walletActions.js:41]: fixed

File: src/apis.js [hunk 46]
```diff
@@ -575,6 +575,29 @@ async function clearTransfer (request: { transferId: string }) {
   }
 }
 
+async function getAllEthContracts () {
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/apis.js:578]: fixed

File: src/apis.js [hunk 47]
```diff
@@ -575,6 +575,29 @@ async function clearTransfer (request: { transferId: string }) {
...
+    const rv = await chainsferApi.post('/ethContracts', {
+      action: 'GET_ALL_CONTRACTS'
+    })
+    return rv.data
+  } catch (err) {
+    throw new Error('Clear transfer failed.')
+  }
+}
+
+async function getEthContract (address: string) {
```
[the remark this answers is not in the document]
Comment (InVincible2016) [reply src/apis.js:589]: fixed

File: src/containers/AccountsManagementContainer.jsx (hunk 7 above)
Comment (InVincible2016) [reply src/containers/AccountsManagementContainer.jsx:88]: fixed

File: src/App.js [hunk 48]
```diff
@@ -335,21 +334,13 @@ class App extends Component {
...
     }
-
+    console.log('window', window)
```
Comment (timothywangdev) [inline src/App.js:343]: remove

File: src/accounts/AccountFactory.js [hunk 49]
```diff
@@ -3,14 +3,11 @@
...
 
 export function createAccount (accountData: AccountData): IAccount {
-  if (['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
-    return new EthereumAccount(accountData)
-  } else if (['bitcoin'].includes(accountData.cryptoType)) {
+  if (accountData.cryptoType === 'bitcoin') {
     return new BitcoinAccount(accountData)
   } else {
-    throw new Error(`Invalid cryptoType: ${accountData.cryptoType}`)
+    return new EthereumAccount(accountData)
```
Comment (timothywangdev) [inline src/accounts/AccountFactory.js:11]: missing cryptoType check

File: src/accounts/EthereumAccount.js [hunk 50]
```diff
@@ -9,14 +9,15 @@ import { getWalletTitle, getWalletConfig } from '../wallet'
...
+import { isERC20 } from '../tokens'
 const PLATFORM_TYPE = 'ethereum'
 
 export default class EthereumAccount implements IAccount<AccountData> {
   accountData: AccountData
 
   constructor (accountData: AccountData) {
-    if (!['ethereum', ...erc20TokensList].includes(accountData.cryptoType)) {
+    const { cryptoType } = accountData
+    if (cryptoType !== 'ethereum' || isERC20(cryptoType)) {
```
Comment (timothywangdev) [inline src/accounts/EthereumAccount.js]:
```suggestion
    if (cryptoType !== 'ethereum' && !isERC20(cryptoType)) {
```

File: src/actions/transferActions.js [hunk 51]
```diff
@@ -49,6 +48,12 @@ async function _getTxFee (txRequest: {
   return txFee
 }
 
+function cryptoTypeCheck (cryptoType) {
+  if (cryptoType && 'bitcoin' && cryptoType !== 'ethereum' && isERC20(cryptoType)) {
```
Comment (timothywangdev) [inline src/actions/transferActions.js]:
```suggestion
  if (cryptoType !== 'bitcoin' && cryptoType !== 'ethereum' && !isERC20(cryptoType)) {
```

File: src/actions/transferActions.js [hunk 52]
```diff
@@ -197,96 +204,92 @@ async function _submitTx (txRequest: {
...
-      // we do not have txHash yet
-      sendTxHash: null,
-      walletId: walletId
-    }
+  let multisig
+  if (cryptoType === 'bitcoin') {
+    walletId = escrowAccount.getAccountData().address
+  } else {
+    walletId = new SimpleMultiSig().createWalletId()
+    multisig = new SimpleMultiSig({ walletId })
```
Comment (timothywangdev) [inline src/actions/transferActions.js:212]:
```suggestion
    multiSig = new SimpleMultiSig({ walletId })
```

File: src/tests/e2e/config.js [hunk 53]
```diff
@@ -0,0 +1 @@
+export const daiAddress = '0x4aacB7f0bA0A5CfF9A8a5e8C0F24626Ee9FDA4a6'.toLowerCase()
```
Comment (timothywangdev) [inline src/tests/e2e/config.js:1]: constant should be uppercase
