### PR TITLE
Resolve #1732 Intercom user incorrect create time

### LINKED ISSUE #1732: Intercom user incorrect create time
not considering rehydration

### PR DESCRIPTION
**Pull request by timothywangdev**

### CODE REVIEW

File: src/trackerMiddleware.js [hunk 1]
```diff
@@ -232,13 +221,13 @@ export const trackerMiddleware = store => next => action => {
...
-      const registerTime =
-        action.payload && action.payload.userReducer && action.payload.userReducer.registerTime
+    case 'POST_LOGIN_PREPARATION_FULFILLED':
+      currentUserId = action.payload.userMetaInfo.googleId
+      const profile = action.payload.userMetaInfo.profile
+      const registerTime = action.payload.userMetaInfo.registerTime
+
       trackUser(currentUserId)
-      intercomLogin(currentUserId, { ...profile.profileObj, registerTime })
+      intercomLogin(currentUserId, { ...profile, registerTime })
```
Comment (InVincible2016) [inline src/trackerMiddleware.js:230]: profile is a UserProfileType from backend, which does not contain email.

Comment (timothywangdev) [reply src/trackerMiddleware.js:230]: This is different, you can check locally
