### PR TITLE
Resolve #969, #970, #978, #982

### LINKED ISSUE #969: Incorrect error msg for password field length check

### PR DESCRIPTION
**Pull request by InVincible2016**

### CODE REVIEW

File: src/components/Stepper.jsx [hunk 1]
```diff
@@ -1,36 +1,126 @@
...
+import StepConnector from '@material-ui/core/StepConnector'
+import Check from '@material-ui/icons/Check'
+import { uiColors } from '../styles/color.js'
 
 const stepsByActionType = {
   receive: ['Security Answer', 'Review', 'Receipt'],
   transfer: ['Set up', 'Review', 'Authorize']
 }
 
+const QontoConnector = withStyles({
```
Comment (timothywangdev) [inline src/components/Stepper.jsx]: Qonto is a company name. Use better name for the style

File: src/components/Stepper.jsx [hunk 2]
```diff
@@ -1,36 +1,126 @@
...
+    }
+  },
+  line: {
+    borderColor: '#eaeaf0',
+    borderTopWidth: 3,
+    borderRadius: 1
+  }
+})(StepConnector)
+
+const useQontoStepIconStyles = makeStyles({
```
Comment (timothywangdev) [inline src/components/Stepper.jsx]: better naming

File: src/components/Stepper.jsx [hunk 3]
```diff
@@ -1,36 +1,126 @@
...
+    backgroundColor: 'currentColor'
+  },
+  completed: {
+    color: uiColors.primary,
+    zIndex: 1,
+    fontSize: 18
+  }
+})
+
+function QontoStepIcon (props) {
```
Comment (timothywangdev) [inline src/components/Stepper.jsx]: better name
