### PR TITLE
Resolve #949, #953

### LINKED ISSUE #949: Pefilled  account doesn't work in transferForm

### PR DESCRIPTION
**Pull request by InVincible2016**

### CODE REVIEW

File: src/reducers/formReducer.js [hunk 1]
```diff
@@ -3,13 +3,10 @@
...
 
 import update from 'immutability-helper'
-import Utils from '../utils'
 
 const initialState = {
-  walletSelection: null,
-  cryptoSelection: null,
   transferForm: {
-    accountSelection: null,
+    accountId: {},
```
Comment (timothywangdev) [inline src/reducers/formReducer.js]: add def comment

Comment (timothywangdev) [reply src/reducers/formReducer.js]: or flow type
