### PR TITLE
Resolve #1139, #1127

### LINKED ISSUE #1139: Direct transfer receipt txHash struct incorrect
```
txHash: {
 txHash: '...'
}
```

should be 
```
txHash: '...'
```

This causes receipt page crash

### PR DESCRIPTION
**Pull request by timothywangdev**

### CODE REVIEW

File: src/actions/transferActions.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ async function _directTransfer (txRequest: {
     .toString()
   const _wallet = createWallet(fromAccount)
 
-  let txHash = await _wallet.sendTransaction({
+  let { txHash }= await _wallet.sendTransaction({
```
Comment (InVincible2016) [inline src/actions/transferActions.js]: This is correct.  https://github.com/ventureum/Chainsfr/blob/master/src/types/wallet.flow.js#L27

Comment (timothywangdev) [reply src/actions/transferActions.js]: inside promise is an object, not a string
