### PR TITLE
Resolve #674 Show security answer in sender's transfer history

### LINKED ISSUE #674: Add "security answer" of each transaction in transaction history
In the user testing, we find that users sometimes forgot or fail to keep/copy the security answers associate with a transaction. To let users better keep track of security answers, we want to add a feature that the "security answer" of each transaction shows in the transaction history.

### PR DESCRIPTION
**Pull request by InVincible2016**
Screen Shot 2019-07-26 at 2 52 27 PM

### CODE REVIEW

File: src/actions/transferActions.js [hunk 1]
```diff
@@ -353,7 +359,9 @@ async function _getTransferHistory (offset: number = 0) {
   }).map(item => {
     let state = null
     let transferType: ?string = null
+    let password: ?string = null
     if (sendingIdsSet.has(item.sendingId)) {
+      password = Base64.decode(passwordDict[item.sendingId]).split(item.sender)[0]
```
Comment (timothywangdev) [inline src/actions/transferActions.js]: why don't we just use

```js
password = transfersDict[item.sendingId].password
```
